/******** DO NOT EDIT THIS FILE ********/
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include "rft_util.h"
#include <stdlib.h>
#include <netinet/in.h> 

/* implementation of checksum function declared in rft_util.h - do NOT edit */
int checksum(char* payload, bool is_corrupted) {
    if (is_corrupted)
        return -rand();
    
    int sum = 0;
    
    for (int i = 0; i < PAYLOAD_SIZE; i++)
        sum += payload[i];

    return sum;
}
